[package]
name = "gioco_della_vita"
version = "0.1.0"
authors = ["roberto"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
